### ISSUE TITLE
I try to import turtlesim.sb3,but throw faile

### ISSUE THREAD

**Issue by zy0228** [Affonso-Gui/scratch3-ros#1]
error log:

gui {"validationError":"Could not parse as a valid SB2 or SB3 project.","sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}],"sb3Errors":[{"keyword":"type","dataPath":".targets[0].variables['9_U%QrPLs9yyowtg4_xp'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf/0/type","params":{"type":"string"},"message":"should be string"},{"keyword":"type","dataPath":".targets[0].variables['9_U%QrPLs9yyowtg4_xp'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf/1/type","params":{"type":"number"},"message":"should be number"},{"keyword":"oneOf","dataPath":".targets[0].variables['9_U%QrPLs9yyowtg4_xp'][1]","schemaPath":"#/definitions/stringOrNumber/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"},{"keyword":"type","dataPath":".targets[0].variables['9_U%QrPLs9yyowtg4_xp'][1]","schemaPath":"#/oneOf/1/type","params":{"type":"boolean"},"message":"should be boolean"},{"keyword":"oneOf","dataPath":".targets[0].variables['9_U%QrPLs9yyowtg4_xp'][1]","schemaPath":"#/oneOf","params":{"passingSchemas":null},"message":"should match exactly one schema in oneOf"}]}
./node_modules/minilog/lib/web/formatters/minilog.js.logger.write @ minilog.js:17
onItem @ transform.js:31
emit @ index.js:26
./node_modules/minilog/lib/common/filter.js.Filter.write @ filter.js:52
onItem @ transform.js:31
emit @ index.js:26
./node_modules/minilog/lib/common/transform.js.Transform.write @ transform.js:15
o.warn @ minilog.js:11
(anonymous) @ sb-file-uploader.jsx:138
Promise.catch (async)
onload @ sb-file-uploader.jsx:136
wrapper @ index.js:550
load (async)
componentWillMount @ sb-file-uploader.jsx:65
callComponentWillMount @ react-dom.development.js:6370
mountClassInstance @ react-dom.development.js:6435
updateClassComponent @ react-dom.development.js:7840
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

**Comment by Affonso-Gui** [comment]
Hello and thanks for the heads up. It seems that we might be having some troubles with the json objects implemented at https://github.com/Affonso-Gui/scratch3-ros-parser.

As specified in the README this repository has been moved to https://github.com/Affonso-Gui/scratch3-ros-vm/tree/develop/src/extensions/scratch3_ros, so can you please repost this issue there so that we can keep the record?

**Comment by Affonso-Gui** [comment]
Moved to https://github.com/Affonso-Gui/scratch3-ros-vm/issues/4
