### ISSUE TITLE
No longer maintain http://scratch3-ros.jsk.imi.i.u-tokyo.ac.jp/ ?

### ISSUE THREAD

**Issue by m-shimizu** [Affonso-Gui/scratch3-ros#2]
I am a heavy user of your scratch3-ros package.
Currently I am using it in my class.
I think the scratch3-ros package is a great job for young ROS users, and I want to keep it under maintenance for long time.

Now, I can not use http://scratch3-ros.jsk.imi.i.u-tokyo.ac.jp/.
Did you leave the famous scratch3-ros site just presenting "いらっしゃいませ“？

If you want to close the site or move the site, please announce your will.

Thanks!

**Comment by Affonso-Gui** [comment]
Hello,

Good to hear from an user.

As explained in the issue below, we got hacked and took the site down as an emergency measure.
https://github.com/Affonso-Gui/scratch3-ros-vm/issues/7

If you have an available PC, we recommend cloning the package and running the server locally. This should be the safest and provide extra flexibility to defining your own extensions if needed.

That being said, we were considering if we should reopen the hosting in http://scratch3-ros.jsk.imi.i.u-tokyo.ac.jp/ , even though we might not be able to make a long-term promise of security (especially considering that the communication with ROS requires an http connection).

**Comment by m-shimizu** [comment]
Dear, Dr.Affonso,

Hi, thank you for your great response!
Hearing from you made me very happy.

Sorry, I did not check deeply on your scratch3-ros packages, and missed the scratch3-ros-vm/issue 7. Now I am feeling sadness at facing such the hacking incident.

Yes, we (I and my class students) need an local scratch3-ros server.
And, we can prepare a PC to run it locally.

I will follow the local install texts on your scratch3-ros repositories and on 
https://github.com/Affonso-Gui/scratch3-ros-vm/issues/7.

Thank you very much.

**Comment by Affonso-Gui** [comment]
Great, please lete know if you have trouble setting it up.


I'll also try to update the readme to better explain the situation and the way to run it locally!

**Comment by m-shimizu** [comment]
It works!
I saw an error in compiling, but it is working.

**What I did:**

    1. Installed nvm, and installed node.js v18.15.0 .
    2. mkdir ~/scratch3-ros
    3. cd ~/scratch3-ros
    4. git clone https://github.com/Affonso-Gui/scratch3-ros-gui  
    5. git clone https://github.com/Affonso-Gui/scratch3-ros-vm  
    6. git clone https://github.com/Affonso-Gui/scratch3-ros-parser  
    7. cd scratch3-ros-parser && npm install && npm link  
    8. cd ../scratch3-ros-vm && npm install && npm link  
    9. cd ../scratch3-ros-gui && npm install && npm link scratch-parser scratch-vm  
    10. npm start  
 

**An error I saw in the final compiling:**

ERROR in unable to locate '~/scrach3-ros/scratch3-ros-gui/node_modules/scratch-vm/dist/web/extension-worker.{js,js.map}' glob
(You can find all messages in [scratch3-ros_compile_error.txt](https://github.com/Affonso-Gui/scratch3-ros/files/13063875/scratch3-ros_compile_error.txt))


**Finally:** 

Even if there was the error, the scratch3-ros server worked correctly. 
I could see the scratch editor GUI and ROS blocks. The scratch editor GUI could load and save scratch files including ROS blocks. Of course, scratch programs including ROS blocks could run and did publish and subscribe some topics with a turtlebot3 in Gazebo.
If you have any idea to fix the error in compile, please let me know it.

Thanks!

**Comment by Affonso-Gui** [comment]
Hello,

I have just pushed some updates to the scratch3-ros-vm and scratch3-ros-gui repositories, which seem to fix the compilation error in my environment.
I am currently on node v18.18.0, but am guessing that it should also be fine with v18.15.0.

Could you clean the directories (remove the `node_modules` folder), update the source and try to rebuild?

**Comment by m-shimizu** [comment]
Thank you for your effort.

It's went well for me.
I saw no error, and my class materials in scratch3 worked well.
I felt that the time took by "npm start" was little bit shorter than the previous one.

Thank you, thank you so much.

Reaching the end of this mail, I write details what I did.

1. Used node version 18.18.0
2. Removed node_modules folder
3. Git pulled the scratch3-ros-gui
  (I know it is needless, but, pulled 
   scratch3-ros-vm and scratch3-ros-parser, too)
4. In the scratch3-ros-parser folder, npm install and link
5. In the scratch3-ros-vm folder, npm install and link 
6. In the scratch3-ros-gui folder, npm install and link scratch-parser scratch-vm 

DOUMO ARIGATO!

**Comment by USeebi** [comment]
We try to introduce ROS to our students with the Scratch3 extension.  I managed to compile the packages running on a desktop PC but we just don't have the necessary resources to put it on a server with required IT supports for ~ 20 to 30 students in a class.

Is there any possibility to compile the whole package as a standalone desktop app or just put the extension online so that it could be loaded from URL?  Any pointer are more than welcome.

**Comment by Affonso-Gui** [comment]
Hello,

I will check the situation once more to see if we can safely restart the http://scratch3-ros.jsk.imi.i.u-tokyo.ac.jp/ domain or distribute it as a standalone package.


In the meantime, would it be possible to run the server program (npm run) on the desktop during the class, and have the students access it from the same network (e.g. http:// 192.168.123.456:8601)?
If you are running it from a windows machine through WSL, you may need to forward the port and/or allow the port connection from your firewall.

```
netsh interface portproxy add v4tov4 listenport=8601 listenaddress=0.0.0.0 connectport=8601 connectaddress=$(wsl hostname -I)
```

**Comment by USeebi** [comment]
Thanks Affonso,

I guess the long term solution is to have a standalone desktop app or loadable extension, it would be unreasonable to expect a non-profit website to be maintained indefinitely.

However, pls actively consider to restart the scratch3-ros website as an interim measure.  BTW, I tried to locate a copy of "A Scratch3 ROS Client for Rapid Developing and Prototyping of Robot Programming Front-End Interfaces" but without success, do u think u could share a preprint copy?

Many thanks!

**Comment by Affonso-Gui** [comment]
Hello,

A standalone seems like a nice long-term solution.
Just in case, could you share a bit more about your use case? What kind of robot are you using / what is the average student age  / what are you expecting from the scratch extension / how are you planning to use it / etc. 

About the paper, please send a request in the following website. It's only a few pages long, so feel free to ask anything unclear.
https://www.researchgate.net/publication/338150418_SCRATCH3-ROS_A_Scratch3_ROS_Client_for_Rapid_Developing_and_Prototyping_of_Robot_Programming_Front-End_Interfaces

**Comment by USeebi** [comment]
Hi there,

We start with Jetracer in our STEM Club and would like to move on with an additional flight controller and help student to learn autonomous robotics with turtlesim.  I'm planning to setup games for students to teleport their turtles to a specific location in Scratch3 while the turtles are in constant motions under ROS server control. Turtlesim in maze would be in the pipeline if the games are success.

For the wish list of the standalone Scratch3-ROS, definitely we need facilities to develop our own extensions just like that in TurboWrap so that a rapid prototyping extension could be loaded either from file or URL.

**Comment by Affonso-Gui** [comment]
Hello,

I have re-uploaded the site in the following domain:
http://www.scratch3ros.com/

(make sure that you are accessing the `http` address, since the `https` won't allow you to connect to the robots through web sockets!)

I have changed the provider and added some more layers of protection, but we still cannot make any promises regarding security.

The site itself should be exactly the same, but please let me know if you run into any problems.
If things go well I'll update the documentation to point to the new site address (while hopefully also working on the standalone)

@USeebi 
@m-shimizu

**Comment by Affonso-Gui** [comment]
> If things go well I'll update the documentation to point to the new site address

done

**Comment by Affonso-Gui** [comment]
Closing this since the site was successfully moved to the following domain:
http://www.scratch3ros.com/
